apiVersion: skaffold/v2alpha3
kind: Config

deploy:
  kubectl:
    manifests:
      - ./infra/*

build:
  local:
    push: false
  artifacts:
    - image: authentication-service
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual: 
        - src: 'app/**/*.py'
          dest: .
    - image: mycontainer
      context: image-generation
      docker:
        dockerfile: Dockerfile
      sync:
        manual: 
        - src: 'app/**/*.py'
          dest: .